name: Build Package
description: Build Debian packages using Docker image

inputs:

  docker_image:
    description: Name of the docker image to use
    required: true

runs:
  using: 'composite'

  steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Spam
      run: echo '${{ inputs.docker_image }}'
      shell: bash

    #- name: Build `*.deb` packages
      #uses: 'docker://${{inputs.docker_image}}'
      #with:
        #entrypoint: ./build.sh
