name: Build and Publish Packages
description: Build Debian packages using CMakeify Me Docker image
author: 'CMakeify Me <cmakeify.me@pm.me>'

inputs:

  docker_image:
    description: Name of the docker image to use
    required: true

runs:
  using: "composite"

  steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: echo docker
      run: echo '${{ inputs.docker_image }}'
      shell: bash

    - name: run docker image input
      run: 'docker run ${{ inputs.docker_image }}'
      shell: bash

#     - name: Build `*.deb` packages
#       uses: '${{ inputs.docker_image }}'
#       with:
#         entrypoint: ./build.sh
